// RSS feed — ports util/rss.js (now generated by @astrojs/rss).
import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';

const FAVICON = 'https://cdn.levine.io/uploads/portfolio/public/images/favicon/favicon.ico';

export async function GET(context) {
  const posts = (await getCollection('writing')).sort(
    (a, b) => b.data.date.valueOf() - a.data.date.valueOf()
  );

  return rss({
    title: "Dave Levine's Writing",
    description: "Latest writing from Dave Levine.",
    site: context.site,
    xmlns: { dc: 'http://purl.org/dc/elements/1.1/' },
    customData: [
      '<language>en</language>',
      `<copyright>All rights reserved ${new Date().getFullYear()}, Dave Levine</copyright>`,
      '<ttl>60</ttl>',
      `<image><url>${FAVICON}</url><title>Dave Levine's Writing</title><link>${context.site}</link></image>`,
      "<generator>Dave Levine's Writing RSS Feed</generator>",
    ].join(''),
    items: posts.map((post) => ({
      title: post.data.title,
      link: `/writing/${post.id}`,
      pubDate: post.data.date,
      description: post.data.description,
      // Same HTML as the page (rehype plugins included: external-link rel, CDN image URLs).
      content: post.rendered?.html ?? '',
      // No custom <guid>: @astrojs/rss uses the item link as a permalink GUID.
      customData: '<dc:creator>Dave Levine</dc:creator>',
    })),
  });
}
